import { expect,test,type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { content } from '../../src/lib/contentRepository';
import { emptyStore } from '../../src/lib/storage';
import { newStudySession,submitSessionItem,selfScoreSessionItem,sessionAttempts,finishSession } from '../../src/lib/studySession';
import { correctIds } from '../../src/lib/questions';
import type { StudySession,ChoiceQuestion } from '../../src/content/types';
const key='ait624-study-progress',single=content.questions.find(q=>q.id==='mcq-1')! as ChoiceQuestion,written=content.questions.find(q=>q.type==='short-answer')!,caseItem=content.cases[0];
const store=(page:Page)=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)||'{}'),key);
async function seed(page:Page,sessions:StudySession[],route:string){await page.goto('/');await page.evaluate(({key,value})=>localStorage.setItem(key,value),{key,value:JSON.stringify({...emptyStore(),studySessions:sessions,attempts:sessions.flatMap(sessionAttempts)})});await page.goto(route);}
function scoredChoice(id:string,right:boolean,date?:string,confidence:'Low'|'Medium'|'High'='High'){
  const answer=right?correctIds(single):[single.choiceIds.find(id=>!correctIds(single).includes(id))!];let s=submitSessionItem(newStudySession('multiple-choice',[single],{autoAdvance:false},id),single.id,answer,confidence);if(date)s.submissions[single.id].submittedAt=date;return s;
}

test('reference sheet edits, reorders, rejects rendered overflow, persists drafts, and prints one Letter page',async({page})=>{
  await page.goto('/cheat-sheet');await expect(page.getByRole('button',{name:'Add note to sheet',exact:true})).toBeDisabled();await page.getByLabel('Sheet title (optional)',{exact:true}).fill('My software engineering reference');await page.getByRole('button',{name:'Save sheet title',exact:true}).click();
  await page.getByRole('textbox',{name:'Reference note text',exact:true}).fill('Validation checks software against customer needs.');await page.getByRole('button',{name:'Add note to sheet',exact:true}).click();await expect(page.getByRole('heading',{name:'Saved notes · 1',exact:true})).toBeVisible();
  await page.getByRole('combobox',{name:'Note style',exact:true}).selectOption('bullet');await page.getByRole('textbox',{name:'Reference note text',exact:true}).fill('Include points toward the included behavior.');await page.getByRole('button',{name:'Add note to sheet',exact:true}).click();await page.getByRole('button',{name:'Move note 2 up',exact:true}).click();expect((await store(page)).referenceSheet.notes[0].text).toContain('Include');
  await page.getByRole('button',{name:'Edit note 2',exact:true}).click();const edited='\nValidation compares the delivered software with customer needs.\n';await page.getByRole('textbox',{name:'Reference note text',exact:true}).fill(edited);await page.getByRole('button',{name:'Save note changes',exact:true}).click();await page.reload();expect((await store(page)).referenceSheet.notes[1].text).toBe(edited);
  const before=(await store(page)).referenceSheet.notes,overflow='One more long reference line.\n'.repeat(80);await page.getByRole('textbox',{name:'Reference note text',exact:true}).fill(overflow);await page.getByRole('button',{name:'Add note to sheet',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'The proposed note exceeds the page'})).toBeVisible();expect((await store(page)).referenceSheet.notes).toEqual(before);await page.reload();await expect(page.getByRole('textbox',{name:'Reference note text',exact:true})).toHaveValue(overflow);
  await page.getByRole('textbox',{name:'Reference note text',exact:true}).fill('W'.repeat(120));await page.getByRole('button',{name:'Add note to sheet',exact:true}).click();await expect(page.getByRole('heading',{name:'Saved notes · 3',exact:true})).toBeVisible();
  const bounds=await page.locator('.sheet-preview-scroll .reference-page').evaluate(el=>({width:el.clientWidth,height:el.clientHeight,font:getComputedStyle(el.querySelector('.reference-content')!).fontSize}));expect(bounds).toEqual({width:816,height:1056,font:'18.6667px'});
  await page.evaluate(()=>{window.print=()=>{document.body.dataset.printCalled='true';};});await page.getByRole('button',{name:'Print / Save as PDF',exact:true}).click();await expect(page.locator('body')).toHaveAttribute('data-print-called','true');
  await page.emulateMedia({media:'print'});const pdf=await page.pdf({path:'test-results/reference-sheet.pdf',format:'Letter',preferCSSPageSize:true,displayHeaderFooter:false,scale:1,printBackground:true});expect((pdf.toString('latin1').match(/\/Type \/Page\b/g)||[])).toHaveLength(1);expect(pdf.toString('latin1')).toMatch(/\/MediaBox \[0 0 612 792\]/);await page.emulateMedia({media:'screen'});
  await page.locator('.sheet-preview-scroll').screenshot({path:'test-results/reference-sheet-preview.png'});const result=await new AxeBuilder({page}).analyze();expect(result.violations.map(v=>({id:v.id,target:v.nodes.map(n=>n.target)}))).toEqual([]);
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByLabel('Enlarge preview to actual size',{exact:true}).check();await expect.poll(()=>page.locator('.sheet-preview-scroll').evaluate(el=>el.scrollWidth>el.clientWidth)).toBe(true);await page.getByLabel('Enlarge preview to actual size',{exact:true}).uncheck();await page.screenshot({path:'test-results/reference-sheet-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Delete note 3',exact:true}).click();await expect(page.getByRole('heading',{name:'Saved notes · 2',exact:true})).toBeVisible();
});

test('suggestion review pauses advancement, adds an edited note, and deduplicates future concept misses',async({page})=>{
  const s=newStudySession('multiple-choice',[single,content.questions.find(q=>q.id==='mcq-2')!],{},'suggestion-session');await seed(page,[s],'/practice/multiple-choice?session=suggestion-session');await page.getByRole('radio').nth(1).check();await page.getByRole('combobox',{name:'Confidence',exact:true}).selectOption('High');await page.getByRole('button',{name:'Submit answer'}).click();
  await expect(page.getByRole('heading',{name:'Suggested reference note',exact:true})).toBeVisible();await page.waitForTimeout(3300);await expect(page.locator('.session-heading')).toContainText('Question 1/2');await page.getByRole('button',{name:'Edit and add',exact:true}).click();
  expect((await store(page)).studySessions[0].pausedItemIds).toContain(single.id);await page.getByRole('combobox',{name:'Note style',exact:true}).selectOption('bullet');await page.getByRole('textbox',{name:'Suggested note text',exact:true}).fill('Validation checks the product against customer needs.');await page.getByRole('button',{name:'Add suggestion to sheet',exact:true}).click();const saved=await store(page);expect(saved.referenceSheet.notes).toHaveLength(1);expect(saved.referenceSheet.notes[0].origin).toBe('edited');expect(saved.suggestionDecisions[0].decision).toBe('added');
  await page.reload();await expect(page.getByRole('heading',{name:'Suggested reference note',exact:true})).toHaveCount(0);
  const repeat=scoredChoice('repeat-suggestion',false);await page.evaluate(({key,session})=>{const data=JSON.parse(localStorage.getItem(key)!);data.studySessions.push(session);localStorage.setItem(key,JSON.stringify(data));},{key,session:repeat});await page.goto('/cheat-sheet');await expect(page.getByRole('heading',{name:'Review your existing reference note',exact:true})).toBeVisible();await page.getByRole('button',{name:'Review and update note',exact:true}).click();await expect(page.locator('.reference-suggestion').getByRole('combobox',{name:'Note style',exact:true})).toHaveValue('bullet');await page.getByRole('textbox',{name:'Suggested note text',exact:true}).fill('My improved validation reminder.');await page.getByRole('button',{name:'Save note changes',exact:true}).click();expect((await store(page)).referenceSheet.notes).toHaveLength(1);
});

test('suggestion dismissal persists; written boundary scores and unfinished mocks reveal no new notes',async({page})=>{
  const low=scoredChoice('dismiss-low',false);let boundary=submitSessionItem(newStudySession('short-answer',[written],{},'boundary'),written.id,'Written answer','Medium');boundary=selfScoreSessionItem(boundary,written.id,2);
  const pending=submitSessionItem(newStudySession('short-answer',[written],{},'pending'),written.id,'Pending answer','High'),mock=submitSessionItem(newStudySession('mock',[single],{},'hidden'),single.id,[single.choiceIds[1]],'High');
  await seed(page,[low,boundary,pending,mock],'/cheat-sheet');await expect(page.locator('.reference-suggestion')).toHaveCount(1);const accessibility=await new AxeBuilder({page}).analyze();expect(accessibility.violations.map(v=>v.id)).toEqual([]);await page.getByRole('button',{name:'Dismiss suggestion',exact:true}).click();await page.reload();await expect(page.locator('.reference-suggestion')).toHaveCount(0);expect((await store(page)).suggestionDecisions[0].decision).toBe('dismissed');
  const finished=finishSession(mock);await page.evaluate(({key,session})=>{const data=JSON.parse(localStorage.getItem(key)!);data.studySessions=data.studySessions.map((s:{id:string})=>s.id===session.id?session:s);localStorage.setItem(key,JSON.stringify(data));},{key,session:finished});await page.reload();await expect(page.locator('.reference-suggestion')).toHaveCount(1);
});

test('sheet backup restores notes and decisions while overflow imports preserve existing data',async({page})=>{
  await seed(page,[scoredChoice('backup-miss',false)],'/cheat-sheet');await page.getByRole('button',{name:'Dismiss suggestion',exact:true}).click();await page.getByRole('textbox',{name:'Reference note text',exact:true}).fill('Keep this note across devices with a backup.');await page.getByRole('button',{name:'Add note to sheet',exact:true}).click();
  const valid=await store(page);await page.goto('/progress');page.on('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Clear personal data',exact:true}).click();await page.getByRole('button',{name:'Confirm clear',exact:true}).click();
  await page.getByLabel('Import backup',{exact:true}).setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(valid))});await expect(page.getByRole('status').filter({hasText:'Backup imported.'})).toBeVisible();expect((await store(page)).referenceSheet.notes).toHaveLength(1);expect((await store(page)).suggestionDecisions).toHaveLength(1);
  const invalid=JSON.parse(JSON.stringify(valid));invalid.referenceSheet.notes[0].text='Overflow line.\n'.repeat(100);await page.getByLabel('Import backup',{exact:true}).setInputFiles({name:'overflow.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await expect(page.getByRole('status').filter({hasText:'reference sheet exceeds one Letter page'})).toBeVisible();expect((await store(page)).referenceSheet.notes).toEqual(valid.referenceSheet.notes);
});

test('failed sheet save keeps saved notes and the proposed edit',async({page})=>{
  await page.goto('/cheat-sheet');await page.getByRole('textbox',{name:'Reference note text',exact:true}).fill('A draft worth preserving.');await expect(page.getByRole('button',{name:'Add note to sheet',exact:true})).toBeEnabled();await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('Quota','QuotaExceededError');};});await page.getByRole('button',{name:'Add note to sheet',exact:true}).click();await expect(page.locator('.storage-alert')).toBeVisible();await expect(page.getByRole('textbox',{name:'Reference note text',exact:true})).toHaveValue('A draft worth preserving.');expect((await store(page)).referenceSheet.notes).toHaveLength(0);
});

test('improvement dashboard separates repeats, self-scores, confidence errors, and version/policy cohorts',async({page})=>{
  const first=scoredChoice('history-first',false,'2026-10-06T12:00:00.000Z','High'),latest=scoredChoice('history-latest',true,'2026-10-08T12:00:00.000Z','Low');
  let c=submitSessionItem(newStudySession('case',[caseItem],{},'history-case'),caseItem.id,'Case answer','High');c=selfScoreSessionItem(c,caseItem.id,1);c.submissions[caseItem.id].submittedAt='2026-10-07T12:00:00.000Z';
  const pending=submitSessionItem(newStudySession('short-answer',[written],{},'history-pending'),written.id,'Pending text','Medium'),mock=submitSessionItem(newStudySession('mock',[single],{},'history-hidden'),single.id,correctIds(single),'High');
  await seed(page,[first,latest,c,pending,mock],'/progress');await page.getByRole('combobox',{name:'History period',exact:true}).selectOption('0');
  await expect(page.locator('.learning-summary .stat').nth(0)).toContainText('4');await expect(page.locator('.learning-summary .stat').nth(0)).toContainText('3 scored · 1 pending');await expect(page.locator('.learning-summary .stat').nth(1)).toContainText('0%');await expect(page.locator('.learning-summary .stat').nth(2)).toContainText('50%');await expect(page.locator('.learning-summary .stat').nth(3)).toContainText('33%');
  await expect(page.getByRole('heading',{name:'High-confidence mistakes · 1',exact:true})).toBeVisible();await expect(page.getByText('1/1 repeated items recovered',{exact:true})).toBeVisible();await expect(page.locator('.trend-table tbody tr')).toHaveCount(2);
  await page.getByRole('combobox',{name:'Evaluation method',exact:true}).selectOption('self');await expect(page.locator('.learning-summary .stat').first()).toContainText('2');await expect(page.getByRole('heading',{name:'High-confidence mistakes · 0',exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Evaluation method',exact:true}).selectOption('all');
  const result=await new AxeBuilder({page}).analyze();expect(result.violations.map(v=>({id:v.id,target:v.nodes.map(n=>n.target)}))).toEqual([]);await page.locator('.learning-trends').screenshot({path:'test-results/learning-trends-desktop.png'});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.locator('.learning-trends').screenshot({path:'test-results/learning-trends-mobile.png'});
});

test('reference sheet and improvement history stay usable offline after caching the fixed font',async({page,context})=>{
  await seed(page,[scoredChoice('offline-history',false)],'/cheat-sheet');await page.getByRole('textbox',{name:'Reference note text',exact:true}).fill('Offline notes use the same fixed font.');await page.getByRole('button',{name:'Add note to sheet',exact:true}).click();await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await context.setOffline(true);await page.reload();await expect(page.getByRole('heading',{name:'Saved notes · 1',exact:true})).toBeVisible();await page.getByRole('textbox',{name:'Reference note text',exact:true}).fill('Another offline note.');await page.getByRole('button',{name:'Add note to sheet',exact:true}).click();await expect(page.getByRole('heading',{name:'Saved notes · 2',exact:true})).toBeVisible();await page.goto('/progress');await expect(page.getByRole('heading',{name:'Improvement and confidence',exact:true})).toBeVisible();await page.getByRole('combobox',{name:'History period',exact:true}).selectOption('0');await expect(page.getByRole('heading',{name:'High-confidence mistakes · 1',exact:true})).toBeVisible();await context.setOffline(false);
});

test('a nearly full sheet stays at fourteen points and a rejected extra line cannot add a print page',async({page})=>{
  const value=emptyStore();value.referenceSheet.title='Boundary sheet';value.referenceSheet.notes=[{id:'boundary-note',kind:'text',text:Array.from({length:34},()=> 'Fixed-size reference line.').join('\n'),origin:'personal',topicIds:[],sourceIds:[],responseIds:[],updatedAt:new Date().toISOString()}];
  await page.goto('/');await page.evaluate(({key,value})=>localStorage.setItem(key,JSON.stringify(value)),{key,value});await page.goto('/cheat-sheet');await expect(page.getByRole('button',{name:'Print / Save as PDF',exact:true})).toBeEnabled();
  await expect(page.getByRole('status').filter({hasText:'about 0 lines remaining'})).toBeVisible();await page.getByRole('textbox',{name:'Reference note text',exact:true}).fill('This extra line should not fit.');await page.getByRole('button',{name:'Add note to sheet',exact:true}).click();expect((await store(page)).referenceSheet.notes).toHaveLength(1);
  await page.emulateMedia({media:'print'});const pdf=await page.pdf({path:'test-results/reference-sheet-near-full.pdf',format:'Letter',preferCSSPageSize:true,displayHeaderFooter:false,scale:1});expect((pdf.toString('latin1').match(/\/Type \/Page\b/g)||[])).toHaveLength(1);expect(await page.locator('.reference-print-root .reference-content').evaluate(el=>getComputedStyle(el).fontSize)).toBe('18.6667px');await page.emulateMedia({media:'screen'});
});

test('font failure blocks capacity-dependent saves and printing while preserving the draft',async({page})=>{
  await page.route('**/fonts/Geist-Regular.ttf',route=>route.abort());
  await page.goto('/cheat-sheet');
  await page.getByRole('textbox',{name:'Reference note text',exact:true}).fill('Preserve this reminder until the fixed font loads.');
  await expect(page.getByRole('button',{name:'Add note to sheet',exact:true})).toBeDisabled();
  await expect(page.getByRole('button',{name:'Print / Save as PDF',exact:true})).toBeDisabled();
  await expect(page.getByRole('button',{name:'Retry font loading'}).first()).toBeVisible();
  expect((await store(page)).referenceSheet.draft.text).toContain('Preserve this reminder');
  await page.unroute('**/fonts/Geist-Regular.ttf');await page.reload();
  await expect(page.getByRole('textbox',{name:'Reference note text',exact:true})).toHaveValue('Preserve this reminder until the fixed font loads.');
  await expect(page.getByRole('button',{name:'Add note to sheet',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'Add note to sheet',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Saved notes · 1',exact:true})).toBeVisible();
});
