'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import type { ReactNode } from 'react';
const links=[['/','Overview','01'],['/blueprint','Exam blueprint','02'],['/study','Study guide','03'],['/practice/multiple-choice','Multiple choice','04'],['/practice/short-answer','Short answer','05'],['/practice/cases','Case studies','06'],['/practice/diagrams','Diagram workspace','07'],['/mock-midterm','Mock midterm','08'],['/progress','Your progress','09']];
export function AppShell({children}:{children:ReactNode}) {
  const path=usePathname();
  return <div className="app-shell"><a className="skip-link" href="#main">Skip to content</a><aside className="sidebar"><Link href="/" className="brand"><span className="brand-mark" aria-hidden="true">s.</span><span>Study Studio<small>SOFTWARE ENGINEERING</small></span></Link><div className="sidebar-label">YOUR STUDY SPACE</div><nav aria-label="Main navigation">{links.map(([href,title,n])=><Link key={href} href={href} aria-current={path===href?'page':undefined}><span className="nav-number">{n}</span>{title}{path===href&&<span className="nav-dot" aria-hidden="true"/>}</Link>)}</nav><div className="sidebar-footer"><span className="live-dot"/> PERSONAL WORKSPACE<p>AIT 624 / COSC 612<br/>Fall 2026 · Towson University</p><small>Progress stays on this browser.</small></div></aside><div className="main-column"><header className="topbar"><span>AIT 624 <span className="muted">/</span> MIDTERM PREPARATION</span><span className="term">FALL 2026</span></header><main id="main" tabIndex={-1}>{children}</main><footer className="page-footer"><span>Built from your course materials. Priorities and practice scores are study aids, not exam predictions.</span><a className="repository-link" href="https://github.com/billymitchell/towson-study-studio" target="_blank" rel="noopener noreferrer">View on GitHub <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a></footer></div></div>;
}
