'use client';
import { useId, useState } from 'react';
import type { Graph } from '@/content/types';
import { arrowKind, edgeDash, relationshipLabel } from '@/lib/diagramNotation';
import { DiagramMarkers } from './DiagramMarkers';
type Issues=Record<string,string[]>;
export function GraphPreview({graph,title='Semantic example',nodeIssues={},edgeIssues={}}:{graph:Graph;title?:string;nodeIssues?:Issues;edgeIssues?:Issues}){
  const [enlarged,setEnlarged]=useState(false);
  const prefix='preview-'+useId().replace(/[^a-zA-Z0-9_-]/g,''),inside=graph.nodes.filter(n=>n.inside),outside=graph.nodes.filter(n=>!n.inside);
  const height=Math.max(350,Math.max(inside.length,outside.length)*140+110);
  const position=(id:string)=>{const n=graph.nodes.find(n=>n.id===id)!;const list=n.inside?inside:outside;return {x:n.inside?510:130,y:105+list.findIndex(x=>x.id===id)*140};};
  function anchor(id:string,toward:{x:number;y:number}){const n=graph.nodes.find(n=>n.id===id)!,p=position(id),dx=toward.x-p.x,dy=toward.y-p.y;const scale=n.kind==='usecase'?1/Math.sqrt((dx/105)**2+(dy/43)**2):Math.min(dx?100/Math.abs(dx):Infinity,dy?43/Math.abs(dy):Infinity);return {x:p.x+dx*scale,y:p.y+dy*scale};}
  return <div className="graph-example"><h4>{title}</h4><div className="preview-actions"><button type="button" className="button secondary" aria-label={(enlarged?'Fit diagram: ':'Enlarge diagram: ')+title} aria-pressed={enlarged} onClick={()=>setEnlarged(v=>!v)}>{enlarged?'Fit diagram':'Enlarge diagram'}</button><small>{enlarged?'Scroll horizontally to inspect labels and arrows.':'Entire diagram shown. Enlarge to inspect labels and arrows.'}</small></div><div className={'diagram-preview-scroll'+(enlarged?' enlarged':'')} tabIndex={0} aria-label={title+' diagram; scroll to inspect'}><svg viewBox={'0 0 820 '+height} role="img" aria-label={title+' showing boundary placement and labeled relationships'}><DiagramMarkers prefix={prefix}/><DiagramMarkers prefix={prefix+'-error'} color="var(--status-error)"/><rect x="340" y="25" width="450" height={height-45} fill="var(--surface-tint)" stroke="var(--tu-graphite)" strokeDasharray="6 4" rx="12"/><text x="360" y="55" fontSize="14" fill="var(--tu-graphite)">SYSTEM BOUNDARY</text>
    {graph.edges.map(e=>{if(!graph.nodes.some(n=>n.id===e.source)||!graph.nodes.some(n=>n.id===e.target))return null;const a=position(e.source),b=position(e.target),same=a.x===b.x;const start=same?{x:a.x+105,y:a.y}:anchor(e.source,b),end=same?{x:b.x+105,y:b.y}:anchor(e.target,a);const path=same?'M '+start.x+' '+start.y+' C '+(a.x+220)+' '+a.y+' '+(b.x+220)+' '+b.y+' '+end.x+' '+end.y:'M '+start.x+' '+start.y+' L '+end.x+' '+end.y;const issues=edgeIssues[e.id]??[],kind=arrowKind(e),color=issues.length?'var(--status-error)':'var(--tu-graphite)',marker=prefix+(issues.length?'-error':'')+'-'+kind;return <g key={e.id} data-relation={e.relation}><path d={path} fill="none" stroke={color} strokeWidth="2.5" strokeDasharray={edgeDash(e)} markerEnd={kind==='none'?undefined:'url(#'+marker+')'}/><text x={same?a.x+185:(start.x+end.x)/2} y={(start.y+end.y)/2-9} fontSize="16" fill={color} textAnchor={same?'end':'middle'} paintOrder="stroke" stroke="var(--tu-white)" strokeWidth="5" strokeLinejoin="round">{relationshipLabel(e)}</text></g>;})}
    {graph.nodes.map(n=>{const p=position(n.id),words=n.label.split(' '),half=Math.ceil(words.length/2),bad=!!nodeIssues[n.id]?.length;return <g key={n.id}>{n.kind==='usecase'?<ellipse cx={p.x} cy={p.y} rx="105" ry="43" fill="var(--tu-white)" stroke={bad?'var(--status-error)':'var(--tu-graphite)'} strokeWidth={bad?3:1.5}/>:<rect x={p.x-100} y={p.y-43} width="200" height="86" rx="7" fill={n.kind==='actor'?'var(--surface-gold)':'var(--tu-white)'} stroke={bad?'var(--status-error)':'var(--tu-graphite)'} strokeWidth={bad?3:1.5}/>}<text x={p.x} y={p.y-8} fontSize="18" fill="var(--tu-black)" textAnchor="middle"><tspan x={p.x}>{words.slice(0,half).join(' ')}</tspan><tspan x={p.x} dy="23">{words.slice(half).join(' ')}</tspan></text></g>;})}
    </svg></div><ul>{graph.nodes.map(n=><li key={n.id} className={nodeIssues[n.id]?.length?'diagram-difference':''}><strong>{n.label||'Unnamed node'}</strong> · {n.kind==='usecase'?'use case':n.kind} · {n.inside?'inside':'outside'} boundary{nodeIssues[n.id]?.map(issue=><span key={issue}>✕ {issue}</span>)}</li>)}</ul><ul>{graph.edges.map(e=><li key={e.id} className={edgeIssues[e.id]?.length?'diagram-difference':''}>{graph.nodes.find(n=>n.id===e.source)?.label} {e.directed?'→':'—'} {graph.nodes.find(n=>n.id===e.target)?.label} · {relationshipLabel(e)}{edgeIssues[e.id]?.map(issue=><span key={issue}>✕ {issue}</span>)}</li>)}</ul><small>Preview spacing is normalized for comparison. Your saved node positions are preserved. Labels and boundary placement determine meaning.</small></div>;
}
