'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { useProgress } from './ProgressProvider';
import { content } from '@/lib/contentRepository';
import { dailyScores, learningMetrics, learningResponses, type HistoryFilters, type LearningResponse } from '@/lib/learningHistory';
const percent=(value:number|null)=>value===null?'—':`${Math.round(value*100)}%`;
function label(response:LearningResponse){return 'title' in response.item?response.item.title:response.item.prompt;}
function localDate(day:string){return new Date(day+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});}
function ScoreChart({points}:{points:ReturnType<typeof dailyScores>}){
  if(!points.length)return <p>No scored responses match this comparison group.</p>;
  const width=760,height=250,left=48,top=20,plotWidth=680,plotHeight=185,dayTime=(day:string)=>Date.parse(day+'T00:00:00Z'),start=dayTime(points[0].day),span=dayTime(points.at(-1)!.day)-start,x=(i:number)=>left+(span===0?plotWidth/2:(dayTime(points[i].day)-start)/span*plotWidth),y=(score:number)=>top+(1-score)*plotHeight;
  const path=points.map((point,i)=>`${i?'L':'M'} ${x(i)} ${y(point.score)}`).join(' ');
  return <div className="trend-chart-scroll"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Daily mean earned points for ${points.length} study days. Exact values and response counts are in the table below.`}>
    {[0,0.5,1].map(value=><g key={value}><line x1={left} x2={left+plotWidth} y1={y(value)} y2={y(value)} stroke="var(--tu-mist)"/><text x={left-10} y={y(value)+5} textAnchor="end">{Math.round(value*100)}%</text></g>)}
    <path d={path} fill="none" stroke="var(--tu-black)" strokeWidth={3}/>{points.map((point,i)=><circle key={point.day} cx={x(i)} cy={y(point.score)} r={5} fill="var(--tu-gold)" stroke="var(--tu-black)"><title>{localDate(point.day)}: {percent(point.score)} from {point.count} responses</title></circle>)}
    <text x={left} y={235}>{localDate(points[0].day)}</text>{points.length>1&&<text x={left+plotWidth} y={235} textAnchor="end">{localDate(points.at(-1)!.day)}</text>}
  </svg></div>;
}
export function LearningTrends(){
  const {data,ready}=useProgress(),[filters,setFilters]=useState<HistoryFilters>({days:30,topicId:'all',evaluation:'all',policy:'all'}),[groupKey,setGroupKey]=useState('');
  const history=useMemo(()=>learningResponses(data),[data.attempts,data.studySessions]),metrics=useMemo(()=>learningMetrics(history,filters),[history,filters]);
  const group=metrics.groups.find(g=>g.key===groupKey)??metrics.groups[0],points=group?dailyScores(group.responses):[];
  const repeated=new Map<string,{response:LearningResponse;count:number}>();
  for(const response of metrics.scored.filter(r=>r.score!<2/3)){const key=`${response.itemId}:${response.itemVersion}:${response.policy}:${response.evaluation}`,old=repeated.get(key);repeated.set(key,{response,count:(old?.count??0)+1});}
  const recurring=[...repeated.values()].filter(r=>r.count>=2).sort((a,b)=>b.count-a.count).slice(0,8);
  if(!ready)return <p role="status">Loading improvement history…</p>;
  return <section className="learning-trends" aria-labelledby="learning-trends-title"><div className="section-heading"><h2 id="learning-trends-title">Improvement and confidence</h2><span>{history.length} saved responses</span></div><p>Explore your saved history. Each response counts once, including cases linked to several chapters. Pending written evaluations stay out of scores; unfinished mock exams stay out of this dashboard.</p>
    <div className="filters trend-filters"><label>History period<select value={filters.days} onChange={e=>setFilters(f=>({...f,days:Number(e.target.value) as 0|7|30}))}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="0">All saved history</option></select></label><label>History chapter<select value={filters.topicId} onChange={e=>setFilters(f=>({...f,topicId:e.target.value}))}><option value="all">All chapters</option>{content.topics.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label><label>Evaluation method<select value={filters.evaluation} onChange={e=>setFilters(f=>({...f,evaluation:e.target.value as HistoryFilters['evaluation']}))}><option value="all">Objective + self-assessed (separate)</option><option value="objective">Objective only</option><option value="self">Self-assessed only</option></select></label><label>History MCQ policy<select value={filters.policy} onChange={e=>setFilters(f=>({...f,policy:e.target.value as HistoryFilters['policy']}))}><option value="all">All policies</option><option value="partial">Partial-credit MCQs only</option><option value="exact">Exact-score MCQs only</option></select></label></div>
    <div className="learning-summary"><div className="stat"><span>SUBMITTED RESPONSES</span><strong>{metrics.selected.length}</strong><small>{metrics.scored.length} scored · {metrics.selected.length-metrics.scored.length} pending</small></div><div className="stat"><span>FIRST-TRY MCQ ACCURACY</span><strong>{percent(metrics.firstAccuracy)}</strong><small>{metrics.first.length} first saved attempts · exact answers</small></div><div className="stat"><span>OBJECTIVE EARNED POINTS</span><strong>{percent(metrics.objectiveMean)}</strong><small>{metrics.scored.filter(r=>r.evaluation==='objective').length} scored responses</small></div><div className="stat"><span>SELF-ASSESSED POINTS</span><strong>{percent(metrics.selfMean)}</strong><small>{metrics.scored.filter(r=>r.evaluation==='self').length} scored responses</small></div></div>
    {!metrics.selected.length&&<p className="note">No revealed responses match these filters. Complete some practice or broaden the history period.</p>}
    <section className="panel"><h3>Score over time</h3><p>Compare one format, evaluation method, content version, difficulty, scoring policy, and practice/exam mode at a time. Daily means describe the attempted mix; they are not a prediction of your exam grade.</p>
      {group?<><label>Comparison group<select value={group.key} onChange={e=>setGroupKey(e.target.value)}>{metrics.groups.map(g=><option key={g.key} value={g.key}>{g.label} · {g.responses.length} responses</option>)}</select></label><ScoreChart points={points}/><div className="table-scroll"><table className="trend-table"><caption>Daily scores · {group.label}</caption><thead><tr><th scope="col">Submission date</th><th scope="col">Mean earned points</th><th scope="col">Responses</th><th scope="col">First attempts</th></tr></thead><tbody>{points.map(point=><tr key={point.day}><td>{localDate(point.day)}</td><td>{percent(point.score)}</td><td>{point.count}</td><td>{point.firstCount}</td></tr>)}</tbody></table></div></>:<p>No scored comparison group yet. Record a score to start a trend.</p>}
      <small>Dates use this browser’s timezone. Written evaluations appear on the original submission date when scored. First-try means first saved submission per item/content version across all history, before these filters; repetitions do not become new first tries.</small>
    </section>
    <section className="panel"><h3>Recovery on repeated questions</h3><p>Match the same item, content version, evaluation method, scoring policy/version, difficulty, and practice mode. Compare its earliest scored response with its latest; the latest must fall within your filters.</p><div className="recovery-grid">{(['objective','self'] as const).map(method=>{const result=metrics.recovery[method];return <div key={method}><h4>{method==='objective'?'Objective recovery':'Self-assessed recovery'}</h4><strong>{result.recovered}/{result.count} repeated items recovered</strong><p>Recovery means moving from below ⅔ to at least ⅔ earned points.</p><small>{result.count<3?'Not enough comparable repeated items for an improvement estimate (need 3).':`${result.delta!>=0?'+':''}${Math.round(result.delta!*100)} percentage points mean change across ${result.count} matched items.`}</small></div>;})}</div></section>
    <section className="panel"><h3>Confidence calibration</h3><p>Does greater confidence line up with more exactly correct answers? Compare objective MCQ accuracy by the confidence you chose before seeing feedback. Low, Medium, and High are labels, not probability estimates.</p><div className="table-scroll"><table><caption>Pre-answer confidence versus exact MCQ accuracy</caption><thead><tr><th scope="col">Confidence</th><th scope="col">Exact accuracy</th><th scope="col">Correct / scored</th></tr></thead><tbody>{metrics.calibration.map(row=><tr key={row.confidence}><th scope="row">{row.confidence}</th><td>{percent(row.accuracy)}</td><td>{row.correct}/{row.count}</td></tr>)}</tbody></table></div><h4>High-confidence mistakes · {metrics.highConfidenceErrors.length}</h4>{metrics.highConfidenceErrors.length?<ul className="confidence-errors">{metrics.highConfidenceErrors.slice(0,8).map(r=><li key={r.id}><span>{label(r)}<small>{percent(r.score)} earned points · not exactly correct · {new Date(r.submittedAt).toLocaleDateString()}</small></span><Link className="text-link" href={`/study?topic=${r.topicIds[0]}`}>Review concept →</Link></li>)}</ul>:<p>No high-confidence MCQ mistakes in this view.</p>}</section>
    <section className="panel"><h3>Chapter gaps</h3><div className="table-scroll"><table><caption>Scores by chapter; a multi-chapter case appears in each applicable chapter</caption><thead><tr><th scope="col">Chapter</th><th scope="col">Scored responses</th><th scope="col">Objective points</th><th scope="col">Self-assessed points</th><th scope="col">First-try MCQ accuracy</th></tr></thead><tbody>{metrics.gaps.map(row=><tr key={row.topic.id}><th scope="row"><Link href={`/study?topic=${row.topic.id}`}>{row.topic.title}</Link></th><td>{row.count}</td><td>{percent(row.objectiveMean)} · n={row.objectiveCount}</td><td>{percent(row.selfMean)} · n={row.selfCount}</td><td>{percent(row.firstAccuracy)} · n={row.firstCount}</td></tr>)}</tbody></table></div><h4>Recurring low scores</h4>{recurring.length?<ul>{recurring.map(({response,count})=><li key={`${response.itemId}:${response.itemVersion}:${response.policy}:${response.evaluation}`}>{label(response)} · {count} scores below ⅔ <Link className="text-link" href={`/study?topic=${response.topicIds[0]}`}>Review topic →</Link></li>)}</ul>:<p>No repeated low-score items in this view yet.</p>}</section>
    {history.some(r=>r.id.startsWith('legacy-case:'))&&<p className="note">Legacy case topic rows with identical answers/confidence recorded in the same second count as one response. Unknown content versions stay in separate comparison groups.</p>}
  </section>;
}
