'use client';
import type { StudySession } from '@/content/types';
import { sessionStats } from '@/lib/studySession';
import { HelpTip } from './HelpTip';
import { useProgress } from './ProgressProvider';
export function SessionHeader({session}:{session:StudySession}){
  const stats=sessionStats(session),{settings,error,pauseAdvance}=useProgress();const hidden=session.mode==='mock'&&session.status==='active';
  return <section className="session-header" aria-label="Study session progress" onMouseOver={e=>{const id=session.items[session.index].id;if((e.target as HTMLElement).closest('.help-trigger')&&session.submissions[id]&&!session.pausedItemIds.includes(id))pauseAdvance(session.id,id);}} onFocusCapture={e=>{if((e.target as HTMLElement).closest('.help-trigger')&&session.submissions[session.items[session.index].id])pauseAdvance(session.id,session.items[session.index].id);}}>
    <div className="session-heading"><strong>Question {session.index+1}/{stats.total}</strong><HelpTip label="Session progress">Question position shows where you are in the fixed queue. The progress bar counts unique submitted items; pending written evaluations are included in submitted progress but excluded from accuracy.</HelpTip><span>{stats.submitted}/{stats.total} submitted · {stats.scored} scored{stats.pending?' · '+stats.pending+' awaiting evaluation':''}</span><span className="save-indicator">{error?'Saving paused':'Saved on this browser'}</span><HelpTip label="Saving your work">Session drafts and submissions save on this browser. Standalone diagram edits require Save diagram. Export a Progress backup before clearing browser data or moving devices. Saving errors pause recording and auto-advance.</HelpTip></div>
    <progress value={stats.submitted} max={stats.total} aria-label="Submitted session questions"/>
    <div className="session-score"><div>{hidden?<><strong>Scores hidden during mock</strong><small>Scores and solutions appear after final submission.</small></>:<><strong>{stats.percent===null?'—':Math.round(stats.percent)+'%'} practice score</strong><HelpTip label="Practice accuracy">Practice score is mean earned points across evaluated items, including partial credit. Exact-answer accuracy counts only completely correct MCQs and is shown separately. A multi-topic case counts once; pending written evaluations are excluded from the denominator. The practice target is your setting, not a predicted exam pass.</HelpTip><span>{stats.correct}/{stats.scored} fully correct scored items</span>{stats.choiceScored>0&&<span>{Math.round(stats.exactPercent!)}% exact-answer accuracy · {stats.exactCorrect}/{stats.choiceScored} MCQs</span>}<small>{stats.percent===null?'Submit and score an item to establish a baseline.':stats.percent>=session.settings.target?'Currently meets your practice target.':'Below your practice target — review the feedback.'} Pending evaluations are excluded.</small></>}<small>MCQ scoring: {session.settings.scoringPolicy==='partial'?'Partial credit':'Exact answer only'} · policy v{session.settings.scoringVersion}. Fixed for this session.</small></div>
    <div className="session-settings"><label>Practice target (%)<input aria-label="Practice target (%)" type="number" min={0} max={100} value={session.settings.target} disabled={!!error} onChange={e=>{const value=Number(e.target.value);if(Number.isInteger(value)&&value>=0&&value<=100)settings(session.id,{target:value});}}/></label><label className="checkbox-label"><input type="checkbox" checked={session.settings.autoAdvance} disabled={!!error||session.status==='completed'} onChange={e=>settings(session.id,{autoAdvance:e.target.checked})}/>Auto-advance after recording</label>{session.mode==='mock'&&<label>Exam advance timing<select value={session.settings.mockAdvance} disabled={!!error||session.status==='completed'} onChange={e=>settings(session.id,{mockAdvance:e.target.value as 'immediate'|'countdown'})}><option value="immediate">Immediately on submit</option><option value="countdown">Three-second countdown</option></select></label>}<HelpTip label="Auto-advance">New mock exams move immediately after a successfully saved response, without waiting for written self-assessment. Choose a countdown or turn off auto-advance for manual navigation. Ordinary practice uses a cancelable three-second countdown and waits for written self-scores. Failed saves never advance. Final mock submission is always explicit.</HelpTip></div></div>
    <small>The target is your practice setting, not a professor-provided passing grade. Progress counts each item once.</small>
  </section>;
}
